# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to clone for slug
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autocommit
# revision_environment = false

# set to 'true' to allow array types to be written in
# the generated migration file
# sourceless = false

# version location specification; this defaults
# to alembic/versions.  when using multiple version
# directories, paths must be separated by spaces
# version_locations = %(here)s/bar %(here)s/bat alembic/versions

# version path separator; as above, this defaults to the character used by os.pathsep.
# shlex compatibility mode is used to parse the path.
# version_path_separator = :

# set to 'true' to search for migrations recursively
# recursive_version_locations = false

# the output encoding used when writing new migration files
# output_encoding = utf-8

sqlalchemy.url = postgresql://postgres:postgres@db:5432/tactivision


[post_write_hooks]
# post_write_hooks defines scripts or python functions that are run
# on newly generated revision scripts.  See the documentation for details.

# logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
